### PR TITLE
Ch. 01: Add hint for enabling internet access when running on Kaggle

### PR DESCRIPTION
**Pull request by MarcusFra**
Just as a proposal regarding the notebook for chapter 01: If the notebooks are run on Kaggle, it might be helpful for one or the other to give a hint on how to enable internet access to be able to clone the repository.

### CODE REVIEW

**Comment by lvwerra** [comment]
Hi @MarcusFra, thanks for the suggestion! 

In my setup I get access automatically when I am logged in. Is that not the case in your setup? In general, I agree that we could add a note about logging in and selecting the GPU when using Kaggle.

**Comment by lewtun** [comment]
Thanks you for the suggestion @MarcusFra! Since this is something that would apply to all the notebooks, I'd prefer to have this information on the README under a new FAQ section, e.g.

```
## FAQ

### How do select a GPU on Kaggle?

Add some explanation here.
```

WDYT @lvwerra ?

**Comment by lvwerra** [comment]
Yep, I also had a note in the Readme in mind! @MarcusFra would you like to have a stab at it? Otherwise I can take over.

**Comment by MarcusFra** [comment]
Thanks. I think it is just the case when initially setting up Kaggle Notebooks. After this is done once, it's preselected/enabled for future sessions. Some people have also reported that they needed to verify their phone number first which was not the case for me (https://www.kaggle.com/product-feedback/63544).

@lvwerra and @lewtun: Sure, I am going to add it to the README.md within a FAQ section!

**Pull request closed without merging**
